# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "xhci_pci" "pata_jmicron" "firewire_ohci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7437ca22-67ad-4ed7-b156-b3e55fa502d5";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/20bc6020-725a-4c42-8409-5c5f6334ae8b";
      fsType = "ext2";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9aa483f4-d20c-451a-952c-688bf9ee3019";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/72ccf7a0-1df8-4839-8641-6fd0d6f1352b"; }
    ];

  nix.maxJobs = 8;
}
